name: 'Build and Push Docker Image'
run-name: ${{ github.actor }} is publishing docker image
on: [push]

env:
  REGISTRY: docker.io
  IMAGE_NAME: plot_finder
  IMAGE_TAG: 0.0.1

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{env.REGISTRY}}
        uses: docker/login-action@v1
        with:
          registry: ${{env.REGISTRY}}
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: ldelab2/plot_finder

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .github/workflows
          push: true
          tags: ldelab2/plot_finder:${{env.IMAGE_TAG}}
          labels: ${{steps.meta.outputs.labels}}








