name: 'Build Docker Image'
run-name: ${{ github.actor }} is building docker image
on: [push]
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        working-directory: .github/workflows
        run: docker build . --file Dockerfile --tag plot_finder

